import type { Answer, CommunityState, Post, User } from "@/lib/types"

export const users: User[] = [
  {
    id: "m-camila",
    name: "Camila Ribeiro",
    email: "camila@leme.pay",
    role: "Head of People",
    company: "Leme Pay",
    city: "São Paulo",
    bio: "People em fintech. Entra na Managerz para falar com gestores, não só com C-level.",
    accent: "oklch(0.55 0.1 250)",
  },
  {
    id: "m-rafael",
    name: "Rafael Mendes",
    email: "rafael@atlas.banco",
    role: "Engineering Manager",
    company: "Atlas Banco",
    city: "Rio de Janeiro",
    bio: "EM de plataforma depois de um ciclo de corte. Quer falar de gente, não só de delivery.",
    accent: "oklch(0.48 0.08 230)",
  },
  {
    id: "m-ana",
    name: "Ana Paula Costa",
    email: "ana@vertice.vc",
    role: "Country Manager",
    company: "Vértice Latam",
    city: "Curitiba",
    bio: "Primeiro ano como country. HQ em Miami, time no Brasil.",
    accent: "oklch(0.5 0.09 20)",
  },
  {
    id: "m-bruno",
    name: "Bruno Oliveira",
    email: "bruno@rotasul.com",
    role: "Head of Operations",
    company: "Rota Sul Logística",
    city: "Campinas",
    bio: "Turnos, SLA e um time que nunca está no mesmo lugar.",
    accent: "oklch(0.46 0.07 160)",
  },
  {
    id: "m-juliana",
    name: "Juliana Ferreira",
    email: "juliana@clara.saude",
    role: "People Manager",
    company: "Clara Saúde",
    city: "Belo Horizonte",
    bio: "1:1s e a conversa que a empresa evita.",
    accent: "oklch(0.58 0.1 350)",
  },
  {
    id: "m-diego",
    name: "Diego Santos",
    email: "diego@feiralivre.app",
    role: "Product Manager",
    company: "Feira Livre",
    city: "Recife",
    bio: "PM manager de marketplace. Mentora quem acabou de ganhar gente.",
    accent: "oklch(0.55 0.1 75)",
  },
  {
    id: "m-marina",
    name: "Marina Alves",
    email: "marina@circuito.co",
    role: "Business Development Manager",
    company: "Alves & Circuito",
    city: "Porto Alegre",
    bio: "Parcerias e quota. Troca hora de BD por hora de people.",
    accent: "oklch(0.42 0.06 250)",
  },
  {
    id: "m-thiago",
    name: "Thiago Lima",
    email: "thiago@casanorte.com",
    role: "Gerente de Operações de Loja",
    company: "Casa Norte",
    city: "Brasília",
    bio: "11 lojas. Quer pares que entendam chão de loja.",
    accent: "oklch(0.5 0.09 140)",
  },
]

const posts: Post[] = [
  {
    id: "q-country-playbook",
    kind: "question",
    authorId: "m-ana",
    title:
      "HQ mandou um playbook global que não cabe no Brasil. Eu ignoro, adapto ou peço guerra?",
    body: "Sou country manager. Miami mandou um playbook de go-to-market que assume SDR americano, ciclo de 90 dias e um legal que não existe aqui. Meu time já sentiu que eu só traduzo slide. Como vocês negociam HQ sem parecer insubordinados — e sem vender um Brasil que não vamos entregar?",
    category: "country-manager",
    createdAt: "2026-09-17T09:10:00-03:00",
  },
  {
    id: "q-pm-ic",
    kind: "question",
    authorId: "m-diego",
    title: "Virei gestor de PMs e continuo sendo o melhor IC do time. Como paro?",
    body: "Toda crise de discovery eu puxo para mim. O time aprende que o caminho rápido sou eu. Quero um rito concreto da primeira semana — não um livro de liderança.",
    category: "product-manager",
    createdAt: "2026-09-16T14:22:00-03:00",
  },
  {
    id: "q-bd-quota",
    kind: "question",
    authorId: "m-marina",
    title:
      "Quota nova, relacionamento antigo: como um BDM não queima a parceria no Q1?",
    body: "A meta subiu 40%. As contas que pagam a casa são as mesmas de sempre. Pressiono agora e estrago 2027, ou protejo o relacionamento e fico olhando para o dashboard em vermelho?",
    category: "business-development",
    createdAt: "2026-09-15T11:05:00-03:00",
  },
  {
    id: "q-estrela",
    kind: "question",
    authorId: "m-diego",
    title: "Meu IC estrela recusou a promoção para gestão — e o RH insiste",
    body: "Ela é a melhor PM individual. Não quer gente. O RH trata como falta de ambição. Preciso de um argumento que não seja 'ela é tímida'.",
    category: "people",
    createdAt: "2026-09-17T10:05:00-03:00",
  },
  {
    id: "q-bypass",
    kind: "question",
    authorId: "m-thiago",
    title: "O diretor fala direto com os encarregados e me esvazia. E agora?",
    body: "Toda segunda ele entra no grupo das lojas, muda prioridade e eu fico sabendo no corredor. Meu time já pergunta se eu ainda decido alguma coisa.",
    category: "varejo",
    createdAt: "2026-09-15T19:40:00-03:00",
  },
  {
    id: "q-hibrido",
    kind: "question",
    authorId: "m-bruno",
    title:
      "Sede em Campinas, operação no Nordeste: cadência sem daily infinita",
    body: "Quem está no escritório ganha contexto. Quem está no hub de Recife ganha o turno ruim. Quero um desenho de semana que não seja mais uma reunião.",
    category: "operacoes",
    createdAt: "2026-09-13T08:15:00-03:00",
  },
  {
    id: "q-decisao",
    kind: "question",
    authorId: "m-rafael",
    title: "Decisão escrita em 15 linhas, antes da reunião. Alguém usa isso fora de engenharia?",
    body: "Peço um parágrafo: contexto, opções, recomendação, o que é irreversível. Se não cabe em 15 linhas, a reunião não existe. Funciona em comercial e people?",
    category: "engenharia",
    createdAt: "2026-09-14T18:05:00-03:00",
  },
  {
    id: "q-11",
    kind: "question",
    authorId: "m-juliana",
    title: "Caderno de 1:1: o que realmente vale anotar — e o que sobe para o diretor",
    body: "Estou cansada de atas que ninguém relê. No meu time o caderno tem três campos: o que a pessoa está carregando, o que eu estou evitando falar, e um combinado de 14 dias. O que vocês deliberadamente deixam de fora?",
    category: "people",
    createdAt: "2026-09-16T09:20:00-03:00",
  },
  {
    id: "hs-juliana",
    kind: "hotseat",
    authorId: "m-juliana",
    title: "Hotseat: o 1:1 que eu evitei por três semanas",
    body: "Estou na cadeira. Caso aberto: um gerente clínico que performa e envenena o time. Perguntem o que o palco normalmente esconde. Eu respondo com o que realmente aconteceu.",
    category: "people",
    createdAt: "2026-09-19T08:00:00-03:00",
    startsAt: "2026-09-19T12:00:00-03:00",
  },
  {
    id: "hs-ana",
    kind: "hotseat",
    authorId: "m-ana",
    title: "Hotseat: primeiro trimestre como country manager",
    body: "Sento na cadeira com números, território e a solidão de quem virou chefe dos antigos pares. Country managers, BDMs e PMs — perguntem.",
    category: "country-manager",
    createdAt: "2026-09-18T10:00:00-03:00",
    startsAt: "2026-09-30T12:00:00-03:00",
  },
]

const answers: Answer[] = [
  {
    id: "a-1",
    postId: "q-country-playbook",
    authorId: "m-marina",
    body: "Não ignore e não faça guerra no Slack. Mande de volta um parágrafo: o que o playbook assume, o que o Brasil entrega, e um piloto de 60 dias. HQ reage melhor a risco nomeado do que a 'aqui é diferente'.",
    createdAt: "2026-09-17T12:40:00-03:00",
  },
  {
    id: "a-2",
    postId: "q-country-playbook",
    authorId: "m-camila",
    body: "Leve duas pessoas do time na call com HQ. Se só você traduz, você vira o filtro. Se o time fala, o playbook encontra o chão.",
    createdAt: "2026-09-17T15:02:00-03:00",
  },
  {
    id: "a-3",
    postId: "q-pm-ic",
    authorId: "m-rafael",
    body: "Na primeira crise, você só faz pergunta. Escreve as três que faria se fosse IC e entrega para o PM dono. Se você resolver, ensinou o time a te esperar.",
    createdAt: "2026-09-16T18:11:00-03:00",
  },
  {
    id: "a-4",
    postId: "q-pm-ic",
    authorId: "m-juliana",
    body: "Marque no 1:1: 'esta semana eu não vou puxar discovery. Onde isso vai doer?' A dor precisa aparecer, senão você continua sendo o atalho.",
    createdAt: "2026-09-17T08:20:00-03:00",
  },
  {
    id: "a-5",
    postId: "q-bd-quota",
    authorId: "m-ana",
    body: "Separe a quota em duas colunas: receita de quem já confia em você e receita de conta nova. Queime só a segunda. A primeira é o país.",
    createdAt: "2026-09-15T16:44:00-03:00",
  },
  {
    id: "a-6",
    postId: "q-estrela",
    authorId: "m-marina",
    body: "Troque ambição por escopo. Escreva a vaga de staff com impacto e compensação iguais às de um gerente júnior. Se o RH não assinar, o problema é a tabela.",
    createdAt: "2026-09-17T15:33:00-03:00",
  },
  {
    id: "a-7",
    postId: "q-bypass",
    authorId: "m-ana",
    body: "20 minutos com o diretor, uma regra: pedido para loja passa por você, ou o SLA que ele cobra não vale. Leve um exemplo da semana, não um manifesto.",
    createdAt: "2026-09-16T09:02:00-03:00",
  },
  {
    id: "a-8",
    postId: "q-decisao",
    authorId: "m-bruno",
    body: "Em operação só funciona se o parágrafo inclui o impacto em turno. Sem isso, a recomendação é opinião de escritório.",
    createdAt: "2026-09-15T07:18:00-03:00",
  },
  {
    id: "a-9",
    postId: "q-11",
    authorId: "m-camila",
    body: "Eu anoto o cansaço real, não o clima corporativo. E o combinado não sobe para o diretor — sobe só o que a pessoa pediu para subir.",
    createdAt: "2026-09-16T14:10:00-03:00",
  },
  {
    id: "a-10",
    postId: "hs-juliana",
    authorId: "m-camila",
    body: "Você falou com o diretor antes de marcar o 1:1, ou foi só você e ele na sala?",
    createdAt: "2026-09-19T12:08:00-03:00",
  },
  {
    id: "a-11",
    postId: "hs-juliana",
    authorId: "m-rafael",
    body: "O que você ensaiou e abandonou na primeira frase?",
    createdAt: "2026-09-19T12:11:00-03:00",
  },
]

const postVotes: Record<string, string[]> = {
  "q-country-playbook": ["m-marina", "m-diego", "m-camila", "m-rafael", "m-bruno", "m-thiago"],
  "q-pm-ic": ["m-rafael", "m-juliana", "m-camila", "m-ana", "m-marina"],
  "q-bd-quota": ["m-ana", "m-diego", "m-camila", "m-thiago"],
  "q-estrela": ["m-marina", "m-juliana", "m-camila", "m-ana"],
  "q-bypass": ["m-ana", "m-bruno", "m-thiago"],
  "q-hibrido": ["m-thiago", "m-diego"],
  "q-decisao": ["m-bruno", "m-diego", "m-camila", "m-ana"],
  "q-11": ["m-camila", "m-ana", "m-diego"],
  "hs-juliana": ["m-camila", "m-rafael", "m-diego", "m-ana", "m-bruno"],
  "hs-ana": ["m-marina", "m-diego", "m-camila"],
}

const answerVotes: Record<string, string[]> = {
  "a-1": ["m-ana", "m-diego", "m-camila", "m-rafael", "m-bruno"],
  "a-2": ["m-ana", "m-juliana"],
  "a-3": ["m-diego", "m-camila", "m-juliana", "m-ana"],
  "a-4": ["m-diego", "m-camila"],
  "a-5": ["m-marina", "m-diego", "m-thiago", "m-camila"],
  "a-6": ["m-diego", "m-camila", "m-juliana", "m-ana", "m-rafael", "m-bruno"],
  "a-7": ["m-thiago", "m-bruno", "m-camila"],
  "a-8": ["m-rafael", "m-diego"],
  "a-9": ["m-juliana", "m-ana", "m-diego"],
  "a-10": ["m-juliana", "m-diego", "m-ana"],
  "a-11": ["m-juliana", "m-camila"],
}

export const seedState: CommunityState = {
  users,
  sessionUserId: null,
  posts,
  answers,
  postVotes,
  answerVotes,
}
